### ISSUE TITLE
Cant start the bot

### ISSUE THREAD

**Issue by nevzs** [dawangraoming/chatgpt-telegram-bot#1]
![Screenshot_20221209-145531_Nekogram X](https://user-images.githubusercontent.com/83658771/206652928-9628f9f1-fd7f-4c76-90b2-73eba7e70dc3.png)
cant start

**Comment by dawangraoming** [comment]
1. check your ChatGPT token is accessible
2. pull the latest code and try again

**Comment by nevzs** [comment]
> 1. check your ChatGPT token is accessible
> 2. pull the latest code and try again

how to running in background?

**Comment by dawangraoming** [comment]
Try to use `pm2` or `docker`

**Comment by nevzs** [comment]
> Try to use `pm2` or `docker`

thankyou

**Comment by nevzs** [comment]
> Try to use `pm2` or `docker`

what command to using pm2?

**Comment by dawangraoming** [comment]
`pm2 start npm --name chatgpt-telegram-bot -- start`
