### ISSUE TITLE
Token是否已经失效了？

### ISSUE THREAD

**Issue by i-iooi-i** [dawangraoming/chatgpt-telegram-bot#4]
大王，请问现在是否手动F12在浏览中获取的session-token已经失效了呢？
尝试填写官方的收费API好像也不行。
一直提示失败~

![image](https://user-images.githubusercontent.com/1827701/207655568-613eff32-c14f-47f4-ae8b-c6c728348539.png)
![image](https://user-images.githubusercontent.com/1827701/207655767-3b5fcfc9-073d-473c-9164-32988d26644f.png)

**Comment by dawangraoming** [comment]
> OpenAI added additional Cloudflare protections that make it more difficult to access the unofficial API. [link](https://github.com/transitive-bullshit/chatgpt-api#update-december-12-2022-)

目前无法使用，且新版 ChatGPT API 无法自动化session，等待社区有更完善的方案后再修复。
